name: Deploy to AWS

on:
  push:
    branches:
      - main  # Trigger deployment on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Logging in to Amazon ECR...
        run: |
          aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 193789491982.dkr.ecr.eu-central-1.amazonaws.com


      - name: Building the Docker image
        run: |
          docker build -t my-python-app .
          docker tag my_flask_app:latest 193789491982.dkr.ecr.eu-central-1.amazonaws.com/email:latest


      - name: Pushing the Image
        run: |
          docker push 193789491982.dkr.ecr.eu-central-1.amazonaws.com/cooking:latest

      - name: Deploy to Amazon ECS
        run: |
          aws ecs update-service --cluster my-cluster --service my-service --force-new-deployment
